% Per-stage training of UNET for grayscale images (greedy optimization)
% To enable gpu training the 'gpus' option must be set.
net = unet_greedy_train([],'name_id','unet_LN','shrink_type','identity', ...
  'step',0.1,'origin',-104,'gpus',[],'plotStatistics',false,'rbf_means', ...
  -100:4:100,'rbf_precision',4,'imdbPath','../../datasets/imdb.mat', ...
  'patchSize',[7 7],'numFilters',48,'zeroMeanFilters',true,'weightNormalization', ...
  true,'noise_std',[5,9,13,17,21,25,29],'solver',@solver.adam,'solverOpts', ...
  struct('beta1',0.9,'beta2',0.999,'eps',1e-4),'learningRate',1e-3*ones(1,100),...
  'numEpochs',30,'batchSize',125,'batchSize_val',125,'alpha',0,'weightSharing', ...
  true,'clb',-100,'cub',100,'lb',0,'ub',255);

% Joint-training of UNET for grayscale images
load('Results/unet_LN-stages:5-psize:7x7@48-WS-std:[5,9,13,17,21,25,29]-solver:adam-greedyTrain/net-final.mat'); 
net = process_net(net); 
net = unet_joint_train(net,'name_id','unet_LN','shrink_type','identity', ...
  'step',0.1,'origin',-104,'gpus',[],'plotStatistics',false,'rbf_means', ...
  -100:4:100,'rbf_precision',4,'imdbPath','../../datasets/imdb.mat', ...
  'patchSize',[7 7],'numFilters',48,'zeroMeanFilters',true,'weightNormalization', ...
  true,'noise_std',[5,9,13,17,21,25,29],'solver',@solver.adam,'solverOpts', ...
  struct('beta1',0.9,'beta2',0.999,'eps',1e-4),'learningRate',[1e-3*ones(1,100)],...
  'numEpochs',200,'batchSize',80,'batchSize_val',80,'alpha',0,'weightSharing', ...
  true,'clb',-100,'cub',100,'lb',0,'ub',255);